services:
  - type: web
    name: sonya-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sonya_bot.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
